# Generated by Django 2.1.4 on 2019-03-05 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, verbose_name='商品类名')),
            ],
            options={
                'verbose_name': '产品分类',
                'verbose_name_plural': '产品分类',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='GoodsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('abstract', models.CharField(max_length=80, verbose_name='商品简介')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='商品价格')),
                ('unit', models.CharField(max_length=30, verbose_name='商品的售卖单位')),
                ('stock', models.IntegerField(default=0, verbose_name='商品库存')),
                ('desc', models.TextField(null=True, verbose_name='详细介绍')),
                ('pic', models.ImageField(upload_to='goods_list/%Y/%m/%d', verbose_name='商品图片')),
                ('popular', models.IntegerField(default=0, verbose_name='人气指数')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goodsapp.CategoryModel', verbose_name='商品的分类')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_name', models.CharField(max_length=30, verbose_name='商品来源')),
                ('origin_pic', models.ImageField(upload_to='goods_origin/', verbose_name='商家logo')),
            ],
            options={
                'verbose_name': '商品源',
                'verbose_name_plural': '商品源',
                'db_table': 'goods_origin',
            },
        ),
        migrations.CreateModel(
            name='MerchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='商家名字')),
                ('href', models.CharField(max_length=155, verbose_name='商家广告链接')),
                ('src', models.ImageField(upload_to='imgs/goods_list/', verbose_name='图片')),
                ('position', models.IntegerField(verbose_name='顺序')),
            ],
            options={
                'verbose_name': '商家广告',
                'verbose_name_plural': '商家广告',
                'db_table': 'merch',
            },
        ),
        migrations.CreateModel(
            name='PackageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='精选套餐名字')),
                ('href', models.CharField(max_length=155, verbose_name='套餐链接')),
                ('src', models.ImageField(upload_to='imgs/goods_list/', verbose_name='广告图片')),
                ('position', models.IntegerField(verbose_name='顺序')),
            ],
            options={
                'verbose_name': '套餐广告',
                'verbose_name_plural': '套餐广告',
                'db_table': 'package',
            },
        ),
        migrations.AddField(
            model_name='goodsmodel',
            name='goods_origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goodsapp.GoodsOrigin', verbose_name='商品源'),
        ),
    ]
