# Generated by Django 2.1.4 on 2019-03-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsorigin',
            name='origin_desc',
            field=models.TextField(default='暂无', verbose_name='商家介绍'),
        ),
    ]
