# Generated by Django 2.1.4 on 2019-03-05 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='未知', max_length=20, verbose_name='专家姓名')),
                ('sex', models.BooleanField(choices=[(1, '男'), (0, '女')], verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('post', models.CharField(max_length=20, null=True, verbose_name='职称')),
                ('professional', models.CharField(max_length=30, verbose_name='专业领域')),
                ('time', models.CharField(max_length=20, null=True, verbose_name='从业时长')),
                ('pic', models.ImageField(upload_to='imgs/expert/', verbose_name='头像')),
                ('desc', models.TextField(verbose_name='个人简介')),
            ],
            options={
                'verbose_name': '专家',
                'verbose_name_plural': '专家',
                'db_table': 'expert',
            },
        ),
        migrations.CreateModel(
            name='Teach_banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='轮播图标题')),
                ('href', models.CharField(max_length=155, verbose_name='广告链接')),
                ('src', models.ImageField(upload_to='imgs/banner/', verbose_name='图片')),
                ('position', models.IntegerField(verbose_name='顺序')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'teach_banners',
            },
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30, verbose_name='视频类别')),
            ],
            options={
                'verbose_name': '视频类别',
                'verbose_name_plural': '视频类别',
                'db_table': 'video_category',
            },
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='课程名称')),
                ('href', models.CharField(max_length=155, verbose_name='视频链接')),
                ('img', models.ImageField(upload_to='imgs/video/', verbose_name='视频图片')),
                ('desc', models.CharField(max_length=255, verbose_name='课程介绍')),
                ('uptime', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('times', models.IntegerField(default=0, verbose_name='视频播放量')),
                ('expert', models.ManyToManyField(to='teachapp.ExpertModel', verbose_name='课程讲师')),
                ('video_category', models.ManyToManyField(default=1, to='teachapp.VideoCategory', verbose_name='视频大类别')),
            ],
            options={
                'verbose_name': '课程视频',
                'verbose_name_plural': '课程视频',
                'db_table': 'video',
            },
        ),
        migrations.CreateModel(
            name='VideoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, verbose_name='视频类型')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='teachapp.VideoCategory', verbose_name='视频大类别')),
            ],
            options={
                'verbose_name': '视频类型',
                'verbose_name_plural': '视频类型',
                'db_table': 'video_type',
            },
        ),
        migrations.AddField(
            model_name='videomodel',
            name='video_type',
            field=models.ManyToManyField(to='teachapp.VideoType', verbose_name='视频类型'),
        ),
    ]
