# Generated by Django 2.1.4 on 2019-03-01 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='采购商名')),
                ('pic', models.ImageField(upload_to='imgs/purchaser/', verbose_name='采购商logo')),
                ('desc', models.TextField(verbose_name='公司介绍')),
            ],
            options={
                'verbose_name': '采购商',
                'verbose_name_plural': '采购商',
                'db_table': 'purchaser',
            },
        ),
        migrations.CreateModel(
            name='PurchProductsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='采购名称')),
                ('pic', models.ImageField(upload_to='imgs/purchs/', verbose_name='采购产品图')),
                ('desc', models.CharField(max_length=255, verbose_name='采购简介')),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cirapp.PurchaserModel', verbose_name='采购商')),
            ],
            options={
                'verbose_name': '采购产品',
                'verbose_name_plural': '采购产品',
                'db_table': 'purch_products',
            },
        ),
    ]
