# Generated by Django 2.1.4 on 2019-03-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchproductsmodel',
            name='count',
            field=models.IntegerField(default='98', verbose_name='采购数量'),
        ),
    ]
