# Generated by Django 2.1.4 on 2019-02-23 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='轮播图标题')),
                ('href', models.CharField(max_length=155, verbose_name='广告链接')),
                ('src', models.ImageField(upload_to='imgs/banner/', verbose_name='图片')),
                ('position', models.IntegerField(verbose_name='顺序')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'banners',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='新闻标题')),
                ('href', models.CharField(max_length=155, verbose_name='新闻链接')),
                ('origin', models.CharField(max_length=30, verbose_name='新闻来源')),
                ('descrip', models.TextField(null=True, verbose_name='新闻简介')),
                ('time', models.CharField(max_length=60, null=True, verbose_name='发布时间')),
                ('picture', models.ImageField(upload_to='news/%Y/%m/%d', verbose_name='新闻配图')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=30, verbose_name='新闻类别')),
            ],
            options={
                'verbose_name': '新闻类型',
                'verbose_name_plural': '新闻类型',
                'db_table': 'newstype',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.ForeignKey(max_length=130, on_delete=django.db.models.deletion.DO_NOTHING, to='jhapp.NewsType', verbose_name='新闻类型'),
        ),
    ]
