# Generated by Django 2.1.4 on 2019-02-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jhapp', '0003_auto_20190223_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=150, verbose_name='新闻标题'),
        ),
    ]
