# Generated by Django 2.1.4 on 2019-03-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jhapp', '0004_auto_20190223_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_title', models.CharField(max_length=30, verbose_name='大标题')),
                ('little_title', models.CharField(max_length=30, verbose_name='小标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('uptime', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('image', models.ImageField(null=True, upload_to='company/%Y/%m/%d', verbose_name='配图')),
            ],
            options={
                'verbose_name': '公司介绍',
                'verbose_name_plural': '公司介绍',
                'db_table': 'company',
            },
        ),
    ]
