# Generated by Django 2.1.4 on 2019-03-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jhapp', '0005_companymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='position',
            field=models.IntegerField(default=1, verbose_name='顺序'),
        ),
    ]
