# Generated by Django 2.1.7 on 2019-05-23 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jhapp', '0006_companymodel_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='活动名称')),
                ('img', models.ImageField(upload_to='action/%Y/%m/%d', verbose_name='活动照片')),
                ('desc', models.CharField(max_length=155, null=True, verbose_name='活动介绍')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='活动时间')),
            ],
            options={
                'verbose_name': '活动细节',
                'verbose_name_plural': '活动细节',
                'db_table': 'action',
            },
        ),
        migrations.CreateModel(
            name='Action_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=30, verbose_name='活动大标题')),
            ],
            options={
                'verbose_name': '活动大标题',
                'verbose_name_plural': '活动大标题',
                'db_table': 'action_type',
            },
        ),
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='获奖名称')),
                ('pic', models.ImageField(upload_to='honor/%Y/%m/%d', verbose_name='获奖照片')),
                ('desc', models.CharField(max_length=155, null=True, verbose_name='获奖介绍')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='获奖时间')),
            ],
            options={
                'verbose_name': '公司荣誉',
                'verbose_name_plural': '公司荣誉',
                'db_table': 'honor',
            },
        ),
        migrations.AddField(
            model_name='action',
            name='action_type',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.DO_NOTHING, to='jhapp.Action_type', verbose_name='公司活动'),
        ),
    ]
